version: "3.9"
services:
  ids-proxy:
    build: ./ids-proxy
    ports:
      - "8081:8081"
    depends_on:
      - demo-app
  demo-app:
    build: ./demo-app
    ports:
      - "5000:5000"
  dashboard:
    build: ./dashboard
    ports:
      - "8080:80"
  attack-sim:
    build: ./attack-sim
    depends_on:
      - ids-proxy
